### ISSUE TITLE
Elephant Art

### ISSUE THREAD

**Issue by kand8998** [anthonyEdu/Stuffed#2]
![image](https://app.gitkraken.com/api/glo/boards/5ebdb1b3a24f5a001181afa6/attachments/5ebdbd187a583d0011368604)

![image](https://app.gitkraken.com/api/glo/boards/5ebdb1b3a24f5a001181afa6/attachments/5ebee4373c5016001671d4a1)

- [x] Adapt proportions of base character in concept to match elephant
- [x] Settle on proportions/style of elephant
- [x] Come up with variations and patterns
- [x] Settle on a pattern (E)

**Comment by anthonyEdu** [comment]
Nice!! it worked!
