### ISSUE TITLE
Bear Art

### ISSUE THREAD

**Issue by Nekokem** [anthonyEdu/Stuffed#4]
![image](https://app.gitkraken.com/api/glo/boards/5ebdb1b3a24f5a001181afa6/attachments/5ebdc2f53c5016001671adee)

- [x] Character Concept
![image](https://app.gitkraken.com/api/glo/boards/5ebdb1b3a24f5a001181afa6/attachments/5ec40daca24f5a00118284ec)

![image](https://app.gitkraken.com/api/glo/boards/5ebdb1b3a24f5a001181afa6/attachments/5ec40e703c50160016727fc2)

**Comment by anthonyromrell** [comment]
I like the panda

**Comment by Nekokem** [comment]
I will be modeling the Panda
